services:
  db:
    image: postgres:15
    container_name: vehicle-db
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"